email_conf:

  username: "346999452@qq.com"
  password: "nhtudwdtqaozbihg"
  host: "smtp.qq.com"

  resource:
    - "xxx.pdf"

  header: ""

  template: "config/mail.html"

damatu:
  username: ""
  password: ""

set:
  station_dates:
    - "2018-03-23"

  station_trains:
    - "D1902"
    - "D1904"
    - "D1906"

  from_station: "成都"
  to_station: "太原"

  seat_type:
    - "二等座"
    - "一等座"

  is_more_ticket: True

  ticke_peoples:
    - "XXX"

  12306count:
    username: ""
    password: ""

  select_refresh_interval: 0.1
  expect_refresh_interval: 0.3
  ticket_black_list_time: 3
  is_aotu_code: False
