email_conf:

  username: "346999452@qq.com"
  password: "nhtudwdtqaozbihg"
  host: "smtp.qq.com"

  resource:
    - "个人简历_甘含颖.pdf"
    - "image/default/我的照片.jpg;image1"
    - "image/default/远程登陆12306.jpg"
    - "image/default/人脸识别.jpg"

  header: "中北大学_测试开发岗_甘含颖"

  template: "config/mail.html"

damatu:
  username: "nfy__"
  password: "346999452"

set:
  station_dates:
    - "2018-03-23"

  station_trains:
    - "D1902"
    - "D1904"
    - "D1906"

  from_station: "成都"
  to_station: "太原"

  seat_type:
    - "二等座"
    - "一等座"

  is_more_ticket: True

  ticke_peoples:
    - "甘含颖"
    - "宋文泰"
    - "徐少伟"

  12306count:
    username: "LT921002191"
    password: "LT921002191LT"

  select_refresh_interval: 0.1
  expect_refresh_interval: 0.3
  ticket_black_list_time: 3
  is_aotu_code: False